### ISSUE TITLE
Update the font for blog titles

### ISSUE THREAD

**Issue by hcristea** [ascentcore/ascentcore.github.io#10]
## Why 

The titles of the blog posts are not rendering in the font expected for the design and it's affecting the user experience

## What 
- [x] Confirm with TJ what's the appropriate font and size for the blog posts 
- [x] Post a comment with the root-cause analysis on why the titles are not rendering with the expected font
- [x] Ensure the blog titles render with the desired font and size

## Notes

You can find the blog posts at https://www.ascentcore.com/insights.html

We currently have 3 entries:
1. https://www.ascentcore.com/2020/03/03/document-cluster.html
2. https://www.ascentcore.com/2020/03/03/react-schema-form.html
3. https://www.ascentcore.com/2021/03/08/ai-adoption.html

**Comment by SebastianMera** [comment]
The titles are rendering with the expected font. Waiting for the appropriate font sand size to be confirmed.

**Comment by hcristea** [comment]
This is implemented. This covered only the blog title fonts. The body text is still rendering with sans-serif. @SebastianMera, please ping TJ to make sure he's aware of the issue.
