### ISSUE TITLE
Update the US address 

### ISSUE THREAD

**Issue by hcristea** [ascentcore/ascentcore.github.io#7]
## Why 

The format the US address appears on the website is not following the standard US address format.

## What 
- [x] Post a comment with all the places where the US address appear on the website
- [x] Ping TJ to give you the exact address format, on separate lines, that he expects to see on the website
- [x] Modify the address to match the format TJ want

## Notes

A snippet from TJ's todo list mention:

> Revise US address (move Reston to next line, add suite 100)

<img width="1038" alt="Screenshot 2021-03-29 at 09 31 15" src="https://user-images.githubusercontent.com/7814406/112795737-9c205180-9071-11eb-8d53-f2ab78d63328.png">

**Comment by SebastianMera** [comment]
The places where the US address appears on our website are in the footer of every page and in the contact page.

**Comment by hcristea** [comment]
This is implemented.
