### ISSUE TITLE
New blog post: Why Schools Should Care About Cybersecurity

### ISSUE THREAD

**Issue by mariasirbu** [ascentcore/ascentcore.github.io#95]
## Why

We want to publish a new blog post on our website.

## What
- [ ] Check if the links to the doc and to the picture work and are accessible
- [ ] Check the quality of the picture (high resolution, jpg) 
   - [ ] Compress image if necessary (use https://tinypng.com/)
   - [ ] Name the image with a SEO friendly name (blog title words separated with hyphens)
- [ ] Create the markdown file for the post with an SEO friendly name

## Article details

- link to the splash image for the blog post: https://drive.google.com/drive/folders/1KtRVrW7G476bpLkWf3YkCPt2goeYCNN1
- link to the google docs with the content: https://docs.google.com/document/d/1NiHFFoeg3d9oYHzZ2Q8qpNJXWtG8-tMmO7FaZKn12Ms/edit

---
title: "Why Schools Should Care About Cybersecurity"
description: "Schools represent one of the institutions which is subject to cyber theft, with their enormous volume of files on their students, personnel, and faculty. Online classes and digital learning have only heightened the need and focus for custom security solutions. In this article, we’ll dive into just a few of the reasons why schools should invest in cybersecurity. "
---

#  Why Schools Should Care About Cybersecurity

The dawn of the digital age has been beneficial to most of the population for a variety of reasons. The Internet has made it possible to go anywhere around the world with the click of a mouse and mobile apps have put food, entertainment, shopping, and so much more in the palm of our hands. Since it is such a ubiquitous part of our lives, we often forget about all the traces of information we leave behind when we sign up for a newsletter, upload photos, or store files on the cloud. 

Unfortunately, cybersecurity criminals are very aware of these vulnerabilities and are always improving on how to take advantage of them. Schools represent one of the institutions which is subject to cyber theft, with their enormous volume of files on their students, personnel, and faculty. Online classes and digital learning have only heightened the need and focus for custom security solutions.

In this article, we’ll dive into just a few of the reasons why schools should invest in cybersecurity. 

## Digital records

This is the first and foremost reason to hire a system architecture designer: to establish security protocols to protect against breaches and cyber-attacks. School records, with sensitive personal information, are often transferred as students change schools or go onto higher education. It’s shockingly easy for cybercriminals to access these records and steal personal information such as social security numbers and home addresses and even modify records to negatively impact students or teachers. Ensuring that schools have cutting edge security protocols to protect this information is crucial to keeping the trust of faculty, students, and their families. 

## Reputation

The field of education is typically seen as credible, honest, and respectable. One negative public event - such as a data breach - could tarnish a school’s reputation for the long-term and gain widespread attention. After all, who would want to attend a school that’s known for sensitive personal information falling into the wrong hands? This could cause teachers, students, and their families to question the trustworthiness of the administrators and negatively impact attendance or funding. 

## Online classes

Cyber attackers can easily strike the networks and platforms that educators use to teach their students, as evidenced by the “Zoom-bombing” incidents seen during the COVID-19 lockdown, where hackers broke into classes and shared offensive content. These attacks can take down a network, scare students and staff, and steal precious learning time. Teachers are most affected in these circumstances because losing teaching hours means squeezing the missed lessons into remaining school days, increasing their workload and stress levels. 

## Legal requirements

All public (and some private depending on their funding) schools must adhere to the many laws and regulations set by the government. To manage these complex requirements while implementing cybersecurity for schools, administrators will need the help of software creators and data protection officers. These experts must be updated on all the changing prerequisites and inform the community on how the school remains compliant with these laws. Included in the data protection officer’s job is ensuring that all programs and applications teachers use for distance learning are protected from cyber-attacks.

## Accountability

Legal issues can arise because of network security incidents caused by cyber hackers, and the costs of these incidents can be very high. Fortunately, there are cybersecurity insurance coverages available but the school is still liable for the network breach, resulting in costly fixes and possible legal fees. While nothing is foolproof, having reliable cybersecurity measures in place can help mitigate this risk and lessen the school’s accountability.

## Conclusion

Installing cybersecurity in schools is necessary to prevent sensitive information about students, teachers, and faculty from falling into the wrong hands. Furthermore, cybersecurity should be prioritized because it can affect the safety and well-being of the entire institution.  

AscentCore is a [software development company](https://www.ascentcore.com/services.html#assessments) that you can trust to guide you to find the right cybersecurity solution for your business or institution. We provide end-to-end services along with our specialized expertise in a wide cross-section of industries to ensure maximum security. Get in touch with us today to see how we can help!

**Comment by SerbanCiprian** [comment]
Done.
